<?php

use App\Model\Car;

$car = Car::fromId($this->id);

$this->headLink()->prependStylesheet('/css/navDetail.css');
$this->headTitle($car->getName());

?>

<h1><?= $car->getName() ?></h1>

<img src="<?= $car->getFullImageUrl() ?>">

<div>
    <table class="table table-borderless">
        <thead>
        <tr>
            <th>Cena prenájmu:</th>
            <td><?= $car->getPrice() ?>€/deň</td>
            <th>Najazdené:</th>
            <td><?= $car->getDrivenKm() ?> km</td>
            <th>Zdvihový objem:</th>
            <td><?= $car->getEngineDisplacement() ?> cm3</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>Značka:</th>
            <td><?= $car->getCarBrand() ?></td>
            <th>Palivo:</th>
            <td><?= $car->getFuelType() ?></td>
            <th>Počet dverí:</th>
            <td><?= $car->getNumberOfDoors() ?></td>
        </tr>
        <tr>
            <th>Model:</th>
            <td><?= $car->getCarModel() ?></td>
            <th>Prevodovka:</th>
            <td><?= $car->hasAutomaticTransmission() ? 'automat' : 'manuál' ?></td>
            <th>Počet sedadiel:</th>
            <td><?= $car->getNumberOfSeats() ?></td>
        </tr>
        <tr>
            <th>Karoséria:</th>
            <td><?= $car->getCarBodywork() ?></td>
            <th>Pohon:</th>
            <td><?= $car->getCarPropulsion() ?></td>
            <th>Farba:</th>
            <td><?= $car->getCarColor() ?></td>
        </tr>
        <tr>
            <th>Rok výroby:</th>
            <td><?= $car->getFabricationDate() ?></td>
            <th>Výkon:</th>
            <td><?= $car->getPower() ?> kW</td>
            <th>Typ výbavy:</th>
            <td><?= $car->getTypeOfEquipment() ?></td>
        </tr>
        </tbody>
    </table>
</div>
