<?php $this->headTitle('Home'); ?>

<form>

</form>


<div class="row">
    <div class="col text-center">
        <h2>Vyberte si svoje auto</h2>
        <p>lOREM ipsum</p>

        <div class="btn-group" role="group">
            <a href="#" class="btn btn-light">Najlepsie ponuky</a>
            <a href="#" class="btn btn-primary">Ekon</a>
            <a href="#" class="btn btn-light">Premium</a>
        </div>
    </div>
</div>

<br>


<div class="row row-cols-1 row-cols-md-4">

    <?php
     $names = [
         'Škoda Octavia Combi',
         'Škoda Octavia',
         'Mazda 3 sedan',
         'Audi A3 sportback',
         'Range Rover',
         'Nissan Qashqai',
         'Seat Ateca',
         'BMW 225xe',
     ];
    ?>

    <?php for ($i = 0; $i <= 7; ++$i) : ?>

    <div class="col mb-4">
        <div class="card text-center">
            <img src="/img/car<?= $i ?>.jpg" class="card-img-top p-3" alt="<?= $names[$i] ?>">
            <div class="card-body">
                <h5 class="card-title"><?= $names[$i] ?></h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

                <div class="btn-group" role="group">
                    <a href="#" class="btn btn-primary">Objednať teraz</a>
                    <a href="#" class="btn btn-secondary">Detaily</a>
                </div>
            </div>
        </div>
    </div>

    <?php endfor; ?>

</div>


<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://docs.zendframework.com/zend-expressive/getting-started/features" target="_blank">
                <i class="fa fa-bolt"></i> Agile &amp; Lean
            </a>
        </h2>
        <p>
            Expressive is fast, small and perfect for rapid application development, prototyping and api's.
            You decide how you extend it and choose the best packages from major framework or standalone projects.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-diactoros" target="_blank">
                <i class="fa fa-exchange-alt"></i> HTTP Messages
            </a>
        </h2>
        <p>
            HTTP messages are the foundation of web development. Web browsers and HTTP clients such as cURL create
            HTTP request messages that are sent to a web server, which provides an HTTP response message.
            Server-side code receives an HTTP request message, and returns an HTTP response message.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-stratigility" target="_blank">
                <i class="fa fa-dot-circle"></i> Middleware
            </a>
        </h2>
        <p>
            Middleware is code that exists between the request and response, and which can take the incoming
            request, perform actions based on it, and either complete the response or pass delegation on to the
            next middleware in the queue. Your application is easily extended with custom middleware created by
            yourself or <a href="https://packagist.org/search/?q=middleware" target="_blank">others</a>.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://docs.zendframework.com/zend-expressive/features/container/intro" target="_blank">
                <i class="fa fa-cube"></i> Containers
            </a>
        </h2>
        <p>
            Expressive promotes and advocates the usage of Dependency Injection/Inversion of Control containers
            when writing your applications. Expressive supports multiple containers which typehints against
            <a href="https://github.com/php-fig/container" target="_blank">PSR Container</a>.
        </p>
        <?php if (isset($this->containerName)) : ?>
            <p>
                <a href="<?= $this->containerDocs ?>" target="_blank">
                    Get started with <?= $this->containerName ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://docs.zendframework.com/zend-expressive/features/router/intro" target="_blank">
                <i class="fa fa-plane"></i> Routers
            </a>
        </h2>
        <p>
            One fundamental feature of zend-expressive is that it provides mechanisms for implementing dynamic
            routing, a feature required in most modern web applications. Expressive ships with multiple adapters.
        </p>
        <?php if (isset($this->routerName)) : ?>
            <p>
                <a href="<?= $this->routerDocs ?>" target="_blank">
                    Get started with <?= $this->routerName ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://docs.zendframework.com/zend-expressive/features/template/zend-view" target="_blank">
                <i class="fa fa-edit"></i> Templating
            </a>
        </h2>
        <p>
            By default, no middleware in Expressive is templated. We do not even provide a default templating
            engine, as the choice of templating engine is often very specific to the project and/or organization.
            However, Expressive does provide abstraction for templating, which allows you to write middleware that
            is engine-agnostic.
        </p>
        <?php if (isset($this->templateName)) : ?>
            <p>
                <a href="<?= $this->templateDocs ?>" target="_blank">
                    Get started with <?= $this->templateName ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>
</div>
