<?php

use App\Model\Car;

$this->headTitle('Domov');

?>

<form>

</form>


<div class="row">
    <div class="col text-center">
        <h2>VYBERTE SI SVOJE AUTO</h2>
        <p>lOREM ipsum</p>

        <div class="btn-group" role="group">
            <a href="#" class="btn btn-light">Najlepsie ponuky</a>
            <a href="#" class="btn btn-primary">Ekon</a>
            <a href="#" class="btn btn-light">Premium</a>
        </div>
    </div>
</div>

<br>


<div class="row row-cols-1 row-cols-md-4">

    <?php foreach (Car::getAll() as $car) : ?>

    <div class="col mb-4">
        <div class="card text-center">
            <img src="<?= $car->getSmallImageUrl() ?>" class="card-img-top p-3" alt="<?= $car->getName() ?>">
            <div class="card-body">
                <h5 class="card-title"><?= $car->getName() ?></h5>
                <span><h4>30€/deň</h4></span>
                <p class="card-text">
                <ul class="text-left">
                    <li><?= $car->getPower() ?> kW</li>
                    <li><?= $car->hasAutomaticTransmission() ? 'automat' : 'manuál' ?></li>
                    <li><?= $car->getDrivenKm() ?> km</li>
                    <li><?= $car->getFuelType() ?></li>
                </ul>
                </p>

                <div class="btn-group" role="group">
                    <a href="#" class="btn btn-primary">Objednať teraz</a>
                    <a href="<?= $this->url('detail', ['id' => $car->getId()]) ?>" class="btn btn-secondary">Detaily</a>
                </div>
            </div>
        </div>
    </div>

    <?php endforeach; ?>

</div>
