<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js')
    ->prependFile('https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.4.1.slim.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <?=$this->headTitle('Car Rental')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 0px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
</head>
<body class="app">
    <div class="app-header">
        <div class="container">
        <nav class="navbar navbar-expand-sm navbar-light bg-white" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        Car Rental
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item1">
                            <a href="#" class="nav-link">
                                Náš tím
                            </a>
                        </li>
                        <li class="nav-item1">
                            <a href="#" class="nav-link">
                                Služby
                            </a>
                        </li>
                        <li class="nav-item1">
                            <a href="#" class="nav-link">
                                Blog
                            </a>
                        </li>
                        <li class="nav-item1">
                            <a href="#" class="nav-link">
                                Kontakt
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fa fa-shopping-cart"></i>
                            </a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        Prihlásenie
                    </span>
                </div>
            </div>
        </nav>
        </div>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; 2019 - <?=date('Y')?> by Martin Kirschbaum. All rights reserved.
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>
